application: alicia-twt
version: 1
runtime: python
api_version: 1

handlers:
- url: /files
  static_dir: files

- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico

- url: .*
  script: alicia-twt.py

skip_files:
- ^(.*/)?\..*
- ^(.*/)?.*\.txt$
- ^(.*/)?.*public\.py$
